 - name: Add jessie-backports repository
   apt_repository:
     repo: deb http://ftp.debian.org/debian stable-backports main
     state: present

 - name: Update cache
   apt:
     update_cache: yes

 - name: Install Kernel 4.
   apt:
     name: linux-image-amd64
     state: latest
     force: yes
     force_apt_get: yes
     default_release: stable-backports
     update_cache: yes
     autoclean: yes

 - name: Reboot to apply new kernel
   reboot:
     reboot_timeout: 120
   tags:
   - kernel

 - name: Update cache
   apt:
     update_cache: yes

 - name: Install packages
   apt:
     name: "{{ packages }}"
     update_cache: yes
   vars:
     packages:
     - mc
     - bc
     - bind9
     - nscd
   tags:
   - packages

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'listen-on-v6'
     replace: 'listen-on'
   tags:
   - dns

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'any'
     replace: '127.0.0.1'
   tags:
   - dns

 - name: Change nameservers
   replace:
     path: /etc/network/interfaces
     regexp: '8.8.8.8'
     replace: '127.0.0.1'
   tags:
     - dns

 - name: Copy resolv.conf
   copy:
     src: resolv.conf
     dest: /etc/resolv.conf
     mode: 0744
   tags:
   - dns

 - name: Restart bind9 service
   service:
     name: bind9
     state: restarted
   tags:
   - dns
