 - name: Add jessie-backports repository
   apt_repository:
     repo: deb http://ftp.debian.org/debian jessie-backports main
     state: present

 - name: Install Kernel 4.
   apt:
     name: linux-image-amd64
     state: latest
     force: yes
     force_apt_get: yes
     default_release: jessie-backports
     update_cache: yes
     autoclean: yes

 - name: Reboot to apply new kernel
   reboot:
     reboot_timeout: 120

 - name: Install packages
   apt:
     name: "{{ packages }}"
   vars:
     packages:
     - mc
     - bc
     - bind9
     - nscd

 - name: Change listening ips
   shell: sed -i 's/listen-on-v6 { any; };/listen-on { 127.0.0.1; };/g' /etc/bind/named.conf.options
   args:
     executable: /bin/bash

 - name: Change nameservers
   shell: sed -i 's/8.8.8.8/127.0.0.1/g' /etc/network/interfaces /etc/resolv.conf
   args:
     executable: /bin/bash

 - name: Restart bind9 service
   service:
    name: bind9
    state: restarted
